name: test

on:
  push:
    branches:
    - master
    - release/*
    - develop
  pull_request:
    branches:
    - master
    - release/*
    - develop

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
       fail-fast: false
       matrix:
         luaVersion: ["5.3"]
    steps:
    - uses: actions/checkout@master
    - uses: leafo/gh-actions-lua@v8
      with:
        luaVersion: ${{ matrix.luaVersion }}
    - uses: leafo/gh-actions-luarocks@v4
    - name: install libyaml
      run: sudo apt-get install libyaml-dev
    - name: install lua dependencies
      run: |
        luarocks install lyaml
        luarocks install luajson
        luarocks install luasocket
        luarocks install luasec
        luarocks install base64
        luarocks install fun
        luarocks install busted
    - name: run unit tests
      run: |
        busted --exclude-tags=system,local spec
