name: test

on:
  push:
    branches:
    - master
    - release-*
    - develop
  pull_request:
    branches:
    - master
    - release-*
    - develop

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
       fail-fast: false
       matrix:
         luaVersion: ["5.3"]
    steps:
    - uses: actions/checkout@master
    - uses: leafo/gh-actions-lua@v8
      with:
        luaVersion: ${{ matrix.luaVersion }}
    - uses: leafo/gh-actions-luarocks@v4
    - name: setup
      run: |
        luarocks install busted
    - name: test
      run: |
        busted --exclude-tags=system,local spec
